import { ContributorData, getTierForScore } from "./trust-scoring";

/**
 * Mock contributor data for development.
 * Demonstrates all 7 trust tiers with realistic profiles.
 */
export const MOCK_CONTRIBUTORS: ContributorData[] = [
  {
    username: "agent-zero",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 94.2,
    tier: getTierForScore(94.2),
    currentStreakType: "approve",
    currentStreakLength: 12,
    totalApprovals: 47,
    totalRejections: 1,
    totalCloses: 0,
    lastEventAt: "2026-02-14T10:00:00Z",
    firstSeenAt: "2025-09-01T00:00:00Z",
    walletAddress: "0xC984...e9EC",
    autoMergeEligible: true,
  },
  {
    username: "milady-core",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 87.5,
    tier: getTierForScore(87.5),
    currentStreakType: "approve",
    currentStreakLength: 8,
    totalApprovals: 35,
    totalRejections: 3,
    totalCloses: 1,
    lastEventAt: "2026-02-13T16:30:00Z",
    firstSeenAt: "2025-10-15T00:00:00Z",
    walletAddress: "0xA1B2...3C4D",
    autoMergeEligible: false,
  },
  {
    username: "eliza-builder",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 76.1,
    tier: getTierForScore(76.1),
    currentStreakType: "approve",
    currentStreakLength: 5,
    totalApprovals: 28,
    totalRejections: 4,
    totalCloses: 2,
    lastEventAt: "2026-02-12T08:00:00Z",
    firstSeenAt: "2025-11-01T00:00:00Z",
    walletAddress: null,
    autoMergeEligible: false,
  },
  {
    username: "steady-contributor",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 63.8,
    tier: getTierForScore(63.8),
    currentStreakType: "approve",
    currentStreakLength: 3,
    totalApprovals: 18,
    totalRejections: 2,
    totalCloses: 1,
    lastEventAt: "2026-02-11T14:00:00Z",
    firstSeenAt: "2025-12-01T00:00:00Z",
    walletAddress: "0xDEAD...BEEF",
    autoMergeEligible: false,
  },
  {
    username: "new-agent-x",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 48.2,
    tier: getTierForScore(48.2),
    currentStreakType: null,
    currentStreakLength: 0,
    totalApprovals: 8,
    totalRejections: 3,
    totalCloses: 1,
    lastEventAt: "2026-02-10T09:00:00Z",
    firstSeenAt: "2026-01-05T00:00:00Z",
    walletAddress: null,
    autoMergeEligible: false,
  },
  {
    username: "first-timer",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 35.0,
    tier: getTierForScore(35.0),
    currentStreakType: "negative",
    currentStreakLength: 1,
    totalApprovals: 2,
    totalRejections: 2,
    totalCloses: 1,
    lastEventAt: "2026-02-08T11:00:00Z",
    firstSeenAt: "2026-01-20T00:00:00Z",
    walletAddress: null,
    autoMergeEligible: false,
  },
  {
    username: "just-arrived",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 35.0,
    tier: getTierForScore(35.0),
    currentStreakType: null,
    currentStreakLength: 0,
    totalApprovals: 0,
    totalRejections: 0,
    totalCloses: 0,
    lastEventAt: null,
    firstSeenAt: "2026-02-14T00:00:00Z",
    walletAddress: null,
    autoMergeEligible: false,
  },
  {
    username: "spam-bot-42",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 8.3,
    tier: getTierForScore(8.3),
    currentStreakType: "negative",
    currentStreakLength: 5,
    totalApprovals: 1,
    totalRejections: 8,
    totalCloses: 4,
    lastEventAt: "2026-02-07T03:00:00Z",
    firstSeenAt: "2026-01-28T00:00:00Z",
    walletAddress: null,
    autoMergeEligible: false,
  },
  {
    username: "speed-demon",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 22.5,
    tier: getTierForScore(22.5),
    currentStreakType: "approve",
    currentStreakLength: 2,
    totalApprovals: 6,
    totalRejections: 0,
    totalCloses: 0,
    lastEventAt: "2026-02-14T02:00:00Z",
    firstSeenAt: "2026-02-12T00:00:00Z",
    walletAddress: null,
    autoMergeEligible: false,
  },
  {
    username: "gone-ghost",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 41.2,
    tier: getTierForScore(41.2),
    currentStreakType: "approve",
    currentStreakLength: 4,
    totalApprovals: 15,
    totalRejections: 1,
    totalCloses: 0,
    lastEventAt: "2025-10-01T00:00:00Z",
    firstSeenAt: "2025-06-01T00:00:00Z",
    walletAddress: "0xCAFE...BABE",
    autoMergeEligible: false,
  },
  {
    username: "security-hero",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 71.4,
    tier: getTierForScore(71.4),
    currentStreakType: "approve",
    currentStreakLength: 3,
    totalApprovals: 12,
    totalRejections: 0,
    totalCloses: 0,
    lastEventAt: "2026-02-13T20:00:00Z",
    firstSeenAt: "2025-12-15T00:00:00Z",
    walletAddress: "0x1234...5678",
    autoMergeEligible: false,
  },
  {
    username: "doc-writer",
    avatarUrl: "https://github.com/ghost.png",
    trustScore: 52.6,
    tier: getTierForScore(52.6),
    currentStreakType: "approve",
    currentStreakLength: 6,
    totalApprovals: 20,
    totalRejections: 0,
    totalCloses: 0,
    lastEventAt: "2026-02-14T05:00:00Z",
    firstSeenAt: "2025-11-10T00:00:00Z",
    walletAddress: null,
    autoMergeEligible: false,
  },
];
